import type React from "react"
import type { Metadata } from "next"
import localFont from "next/font/local"
import { Sidebar } from "@/components/dashboard/Sidebar"
import { UserNav } from "@/components/UserNav"
import { Notifications } from "@/components/Notifications"
import { TopBar } from "@/components/TopBar"
import "./globals.css"

// Fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex h-screen overflow-hidden">
          <Sidebar />
          <div className="flex-1 flex flex-col overflow-hidden">
            <header className="flex items-center justify-between px-6 py-4 border-b">
              <TopBar />
              <div className="flex items-center space-x-4">
                <Notifications />
                <UserNav />
              </div>
            </header>
            <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-100 p-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  )
}
